name: cicd-gc

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/go-web-service/go-web-service

jobs:
  cicd:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:

    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t ${{ env.IMAGE_NAME }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Deploy Docker image
      run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image ${{ env.IMAGE_NAME }} --region us-central1 --platform managed