name: manual-deploy

on:
  workflow_dispatch:
    inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
    tags:
      description: 'Test scenario tags'


env:
  IMAGE_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/go-web-service/go-web-service:latest

jobs:
  cicd:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest

    steps:

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t ${{ env.IMAGE_NAME }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Deploy Docker image
      run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image ${{ env.IMAGE_NAME }} --region us-central1 --platform managed